/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package invoiceIT;

/**
 *
 * @author günter
 */
import de.abas.ceks.jedp.*;
import java.net.URI;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import microsoft.exchange.webservices.data.Appointment;
import microsoft.exchange.webservices.data.CalendarFolder;
import microsoft.exchange.webservices.data.CalendarView;
import microsoft.exchange.webservices.data.ExchangeService;
import microsoft.exchange.webservices.data.ExchangeVersion;
import microsoft.exchange.webservices.data.FindItemsResults;
import microsoft.exchange.webservices.data.WebCredentials;
import microsoft.exchange.webservices.data.WellKnownFolderName;


public class Einstellungen extends javax.swing.JDialog {

    /**
     * Creates new form Einstellungen
     */
    public Einstellungen(java.awt.Frame parent, boolean modal, String edpHost, String edpPort, String edpMandant, String edpPasswort,String mitarbeiter,String exchange,String exchuser,String exchpass, String internFirma,
                        boolean OpenTreeKunde, boolean ExchangeCalSuche,String updateLocation, boolean Filosofie) {
        super(parent, modal);
        initComponents();
        
         jHostField.setText(edpHost);
        jPortField.setText(edpPort);
        jMandantField.setText(edpMandant);
        jPasswordField.setText(edpPasswort);
        jMitarbeiterField.setText(mitarbeiter);
        jExchangeServer.setText(exchange);
        jExchangeUser.setText(exchuser);
        jExchangePass.setText(exchpass);
        jFirma.setValue(internFirma);
        jOpenTreeKunden.setSelected(OpenTreeKunde);
         jCheckExchangeSuch.setSelected(ExchangeCalSuche);
        // jLabel10.setText("Update suchen auf");
         jUpdateLocation.setText(updateLocation);
         jFilosofie.setSelected(Filosofie);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jUpdateLocation = new javax.swing.JTextField();
        jOpenTreeKunden = new javax.swing.JCheckBox();
        jFirma = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFilosofie = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jHostField = new javax.swing.JTextField();
        jPortField = new javax.swing.JTextField();
        jMandantField = new javax.swing.JTextField();
        jMitarbeiterField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEdpTest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jExchangeServer = new javax.swing.JTextField();
        jExchangeUser = new javax.swing.JTextField();
        jExchangePass = new javax.swing.JPasswordField();
        jCheckExchangeSuch = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jExchangeTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFirma.setModel(new javax.swing.SpinnerListModel(new String[] {"GmbH & Co. KG.", "eSolutions", "Nürnberg"}));
        jFirma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setText("Firma");

        jLabel10.setText("Baum expandieren beim Start");

        jLabel11.setText("Update suchen auf");

        jLabel12.setText("\"Filosofie\" des Tages");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFilosofie)
                    .addComponent(jOpenTreeKunden)
                    .addComponent(jFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jOpenTreeKunden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFilosofie)
                    .addComponent(jLabel12))
                .addGap(161, 161, 161))
        );

        jTabbedPane1.addTab("Allgemein", jPanel1);

        jLabel1.setText("Host");

        jLabel2.setText("edp Port");

        jLabel3.setText("Mandant");

        jLabel4.setText("Passwort");

        jLabel5.setText("Mitarbeitername");

        jEdpTest.setText("Verbindung testen");
        jEdpTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdpTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jHostField)
                            .addComponent(jPortField)
                            .addComponent(jMandantField)
                            .addComponent(jMitarbeiterField)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jEdpTest)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMandantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMitarbeiterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEdpTest)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EDP", jPanel2);

        jCheckExchangeSuch.setText("Kalendereintrag verknüpfen über Suchwort");

        jLabel6.setText("Exchange Adresse");

        jLabel7.setText("Exchange User");

        jLabel8.setText("Exchange Passwort");

        jExchangeTest.setText("Exchange testen");
        jExchangeTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExchangeTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckExchangeSuch)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jExchangeServer)
                        .addComponent(jExchangeUser)
                        .addComponent(jExchangePass, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExchangeTest)
                .addGap(201, 201, 201))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jExchangeServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExchangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jExchangePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckExchangeSuch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jExchangeTest)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exchange", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEdpTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdpTestActionPerformed
        try {
            // Verbindung testen zum Server via edp
             EDPSession session = EDPFactory.createEDPSession(3.31);
             String passwd = new String(jPasswordField.getPassword());
             Integer edpport = Integer.parseInt(jPortField.getText());
             //Session aufbauen
             session.beginSession(jHostField.getText(), edpport, jMandantField.getText(), passwd, "JEDP_0001");
             session.endSession();
             JOptionPane.showMessageDialog(this, "Verbindungsaufnahme erfolgreich");
        } catch (CantBeginSessionException ex) {
            Logger.getLogger(Einstellungen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Verbindungsaufnahme gescheitert\n\n" + ex, "EDP Fehler", JOptionPane.ERROR_MESSAGE);
        }          
    }//GEN-LAST:event_jEdpTestActionPerformed

    private void jExchangeTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExchangeTestActionPerformed
              try {
            ExchangeService service = null;   
            String passwd = new String(jExchangePass.getPassword());    
            if ((!jExchangeServer.getText().equals("")) && (!jExchangeUser.getText().equals("")) && (!passwd.equals("")))
            {          
                                 service = new ExchangeService(ExchangeVersion.Exchange2010_SP1);
                    }     
                //service.setUrl(new URI("https://topas/ews/Exchange.asmx"));         
                service.setUrl(new URI(jExchangeServer.getText()));       
                service.setCredentials(new WebCredentials(jExchangeUser.getText(), passwd));   
                
                Date now = new Date();
		Calendar calendar = new GregorianCalendar();
		calendar.setTime(now);

		// add 50 days to calendar instance
		calendar.add(Calendar.DAY_OF_MONTH, 50);

		// get the date instance
		Date endDate = calendar.getTime();
                // add -100 days to calendar instance
		calendar.add(Calendar.DAY_OF_MONTH, -100);
                
		// get the date instance
		Date startDate = calendar.getTime();
                System.out.println(startDate);

                SimpleDateFormat xformatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                CalendarFolder cf=CalendarFolder.bind(service, WellKnownFolderName.Calendar);
                FindItemsResults<Appointment> findResults = cf.findAppointments(new CalendarView(startDate, endDate));
                for (Appointment appt : findResults.getItems())
{
               
                        
               
                    //Alles ok, Verbindung läuft
               
                    
            	System.out.println("SUBJECT====="+appt.getSubject());
            	//System.out.println("BODY========"+appt.getBody());
                }
                
                
                JOptionPane.showMessageDialog(this, "Verbindungsaufnahme erfolgreich");
        } catch (Exception ex) {
            Logger.getLogger(Einstellungen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Verbindungsaufnahme gescheitert\n\n" + ex, "Exchange Fehler", JOptionPane.ERROR_MESSAGE);       
        }
    
    

    }//GEN-LAST:event_jExchangeTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Einstellungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Einstellungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Einstellungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Einstellungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Einstellungen dialog = new Einstellungen(new javax.swing.JFrame(), true,"", "", "", "","","","","","",false,false,"",true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
      String getHost() {
        return jHostField.getText();

    }

    int getPort() {
        return Integer.parseInt(jPortField.getText());
    }

    String getMandant() {
        return jMandantField.getText();
    }

    String getPasswort() {
        String passwd = new String(jPasswordField.getPassword());
        return passwd;
    }
    
      String getMitarbeiter() {
           return jMitarbeiterField.getText();
    }
String getExchange() {
           return jExchangeServer.getText();
    }
String getExchuser() {
           return jExchangeUser.getText();
    }
String getExchpass() {
     String passwd= new String(jExchangePass.getPassword());       
    return passwd;
    }

String getFirma() {
             
    return jFirma.getValue().toString();
    }
String getUpdateLocation() {
             
    return jUpdateLocation.getText();
    }

boolean getTreeOpenKunde() {
             
    return jOpenTreeKunden.isSelected();
    }
boolean getExchangeCalSuche() {
             
    return jCheckExchangeSuch.isSelected();
    }

boolean getFilosofie() {
    return jFilosofie.isSelected();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckExchangeSuch;
    private javax.swing.JButton jEdpTest;
    private javax.swing.JPasswordField jExchangePass;
    private javax.swing.JTextField jExchangeServer;
    private javax.swing.JButton jExchangeTest;
    private javax.swing.JTextField jExchangeUser;
    private javax.swing.JCheckBox jFilosofie;
    private javax.swing.JSpinner jFirma;
    private javax.swing.JTextField jHostField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMandantField;
    private javax.swing.JTextField jMitarbeiterField;
    private javax.swing.JCheckBox jOpenTreeKunden;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jPortField;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jUpdateLocation;
    // End of variables declaration//GEN-END:variables
}
